apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    app: dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer